### ISSUE TITLE
Not enough tests

### ISSUE THREAD

**Issue by ematta** [jkulton/topical#7]
Don't be this dude...
![image](https://user-images.githubusercontent.com/220164/112905613-50d96380-90b0-11eb-86e6-1e704fb72601.png)

**Comment by jkulton** [comment]
See #8 for improved unit test coverage and addition of integration tests for storage layer.

**Comment by jkulton** [comment]
Added GH Action which runs `go build` and `go test` on commits.

PRs must have a successful status checks of this GH Action before being merged.

**Comment by jkulton** [comment]
Merged #8
